export const RED_CHANNELS = 'RED_CHANNELS';
export const RED_CURRENT_CHANNEL = 'RED_CURRENT_CHANNEL';
export const RED_SINGLE_CHANNEL = 'RED_SINGLE_CHANNEL';
export const RED_CHANNEL_MESSAGES = 'RED_CHANNEL_MESSAGES';
export const RED_CHANNEL_USERS = 'RED_CHANNEL_USERS';
